baseURL = "https://soroushbgh.github.io/my_blog/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anatole'


[params]
title = "I'm Kir khar"
author = "Soroush Kiri"
description = "Call me Koni"
profilePicture = "images/profile.png"

 [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

# ==========================================

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/soroush-bagheri-b5b383103/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/SoroushBgh"

[[params.socialIcons]]
icon = "fab fa-envelope"
title = "mail"
url = "mailto:bghsoroush@gmail.com"

