baseURL = "https://soroushbgh.github.io/my_blog/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anatole'


[params]
title = "I'm Kir khar"
author = "Soroush Kiri"
description = "Call me Koni"
profilePicture = "images/profile.jpg"